// Conjunto curado de emojis para el selector de íconos de las páginas de la
// Wiki, agrupados por categoría y con palabras clave en español (e inglés)
// para poder buscarlos por palabra, no solo por vista.
export type WikiEmoji = { emoji: string; keywords: string };
export type WikiEmojiCategory = { name: string; emojis: WikiEmoji[] };

const C = (name: string, entries: Array<[string, string]>): WikiEmojiCategory => ({
  name,
  emojis: entries.map(([emoji, keywords]) => ({ emoji, keywords })),
});

export const WIKI_EMOJI_CATEGORIES: WikiEmojiCategory[] = [
  C('Caras', [
    ['😀', 'cara sonriente happy smile contento feliz alegre'],
    ['😃', 'alegria joy gran sonrisa'],
    ['😄', 'risa laugh sonrisa feliz'],
    ['😁', 'sonrisa dientes smile contento'],
    ['😆', 'carcajada lol laughing jaja'],
    ['😂', 'lagrimas alegria joy tears risa'],
    ['🤣', 'carcajada laughing rodando'],
    ['😊', 'sonrisa feliz contento sonrojado'],
    ['😇', 'angel halo santo inocente'],
    ['🙂', 'sonrisa suave smile'],
    ['🙃', 'cara al reves upside down'],
    ['😉', 'guino wink sonrisa'],
    ['😌', 'aliviado relieved calmado'],
    ['😍', 'enamorado enamorada love ojos corazon'],
    ['🥰', 'carino adorar afecto smiles'],
    ['😘', 'besito beso kiss volado'],
    ['😋', 'rico delicioso tasty lengua'],
    ['😛', 'lengua burla tongue broma'],
    ['😝', 'lengua ojo burla playful'],
    ['🤪', 'loco crazy divertido'],
    ['🤨', 'dudando dudoso skeptical ceja'],
    ['🧐', 'investigando detective lupa'],
    ['😐', 'neutral cara seria'],
    ['😑', 'sin expresion expressionless'],
    ['😶', 'sin palabras sinhabla'],
    ['😏', 'sonrisa picara smirk complicidad'],
    ['😒', 'no me gusta unamused enfadado'],
    ['🙄', 'ojos en blanco roll eyes'],
    ['😬', 'mueca grimace nervioso dientes'],
    ['🤥', 'mentiroso liar pinocho nariz'],
    ['😴', 'dormido sleep sueno cansado'],
    ['🤤', 'babeando drool sueno'],
    ['😪', 'somnoliento sleepy cansado'],
    ['😷', 'enfermo mascarilla mask resfrio'],
    ['🤒', 'termometro fiebre enfermo'],
    ['🤕', 'vendaje venda lesionado'],
    ['🤢', 'asco nauseas nauseado'],
    ['🤮', 'vomito vomit enfermo'],
    ['🥵', 'calor caliente heat sofoco'],
    ['🥶', 'frio cold hielo'], 
    ['😱', 'gritando scream horror miedo'],
    ['😨', 'asustado miedo fear sorprendido'],
    ['😰', 'sudor nervioso anxious preocupado'],
    ['😥', 'triste decepcionado worried apenado'],
    ['😢', 'llorando llorar llanto crying triste'],
    ['😭', 'llanto profundo sobbing lagrimas'],
    ['😤', 'enfadado frustrado fumando'],
    ['😡', 'enojado angry rojo furioso'],
    ['🤬', 'insultos swear maldiciendo'],
    ['😳', 'sonrojado verguenza ashamed'],
    ['🤗', 'abrazo hug abrazando'],
    ['🤔', 'pensando pensar think duda'],
    ['🤭', 'tapando boca morder lips'],
    ['🤫', 'silencio shh calla'],
    ['😎', 'guay cool gafas sol'],
    ['🤓', 'nerd friki gafas'],
    ['🤩', 'asombrado wow estrella ojos'],
    ['🥳', 'celebracion fiesta celebrate'],
    ['🥺', 'suplicando porfavor mirada'],
    ['🤠', 'vaquero cowboy sombrero'],
    ['🤡', 'payaso clown circo'],
    ['👻', 'fantasma ghost halloween'],
    ['👽', 'alien extraterrestre'],
    ['🤖', 'robot tecnologia'],
    ['💀', 'calavera skull muerte peligro'],
    ['👋', 'saludar hola adios wave mano'],
    ['🤚', 'mano levantada raised'],
    ['✋', 'mano alto stop palma'],
    ['👌', 'perfecto ok genial perfect'],
    ['🤏', 'pellizco poco pinch'],
    ['🤙', 'llamame call shaka'],
    ['👈', 'izquierda left apuntar'],
    ['👉', 'derecha right apuntar'],
    ['👆', 'arriba up apuntar'],
    ['👇', 'abajo down apuntar'],
    ['👍', 'pulgar arriba gustar like genial'],
    ['👎', 'pulgar abajo no gusta dislike'],
    ['✊', 'sena puno fist saludo'],
    ['👊', 'puno punetazo punch boxeo'],
    ['👏', 'aplausos aplauso clap felicitaciones'],
    ['🙌', 'manos arriba celebrar brazos'],
    ['🤝', 'apreton de manos handshake trato acuerdo'],
    ['🙏', 'gracias por favor oracion plegaria pray'],
  ]),
  C('Corazones', [
    ['❤️', 'corazon rojo heart amor love'],
    ['🧡', 'corazon naranja'],
    ['💛', 'corazon amarillo'],
    ['💚', 'corazon verde'],
    ['💙', 'corazon azul'],
    ['💜', 'corazon lila morado'],
    ['🖤', 'corazon negro'],
    ['🤍', 'corazon blanco'],
    ['🤎', 'corazon marron'],
    ['💔', 'corazon roto broken roto'],
    ['💕', 'corazones dobles two hearts'],
    ['💞', 'corazones girando revolving'],
    ['💓', 'corazon latiendo latido heartbeat'],
    ['💗', 'corazon creciente growing'],
    ['💖', 'corazon brillante sparkling'],
    ['💘', 'corazon flecha arrow enamorar'],
    ['💝', 'caja regalo corazon gift present'],
    ['💟', 'corazon decorativo'],
    ['❤️‍🔥', 'corazon fuego fire pasion'],
    ['❤️‍🩹', 'corazon vendaje sanar heal'],
    ['💯', 'cien puntos 100 perfecto'],
  ]),
  C('Animales y naturaleza', [
    ['🐶', 'perro dog mascota cachorro'],
    ['🐱', 'gato cat gatito'],
    ['🐭', 'raton mouse'],
    ['🐹', 'hamster'],
    ['🐰', 'conejo rabbit conejito'],
    ['🦊', 'zorro fox'],
    ['🐻', 'oso bear peluche'],
    ['🐼', 'panda'],
    ['🐨', 'koala'],
    ['🐯', 'tigre tiger'],
    ['🦁', 'leon lion rey'],
    ['🐮', 'vaca cow leche'],
    ['🐷', 'cerdo pig cerdito'],
    ['🐸', 'rana frog'],
    ['🐵', 'mono monkey'],
    ['🐔', 'gallina pollo chicken'],
    ['🐧', 'pinguino penguin'],
    ['🐦', 'pajaro bird'],
    ['🐤', 'pollito chick'],
    ['🦆', 'pato duck'],
    ['🦅', 'aguila eagle'],
    ['🦉', 'buho owl sabio'],
    ['🦇', 'murcielago bat'],
    ['🐺', 'lobo wolf'],
    ['🐴', 'caballo horse'],
    ['🦄', 'unicornio unicorn'],
    ['🐝', 'abeja bee miel honey'],
    ['🦋', 'mariposa butterfly'],
    ['🐌', 'caracol snail'],
    ['🐞', 'mariquita ladybug'],
    ['🐜', 'hormiga ant'],
    ['🐢', 'tortuga turtle'],
    ['🐍', 'serpiente snake'],
    ['🦎', 'lagarto lizard'],
    ['🦀', 'cangrejo crab'],
    ['🦐', 'gamba camaron shrimp'],
    ['🐙', 'pulpo octopus'],
    ['🦑', 'calamar squid'],
    ['🐬', 'delfin dolphin'],
    ['🐋', 'ballena whale'],
    ['🦈', 'tiburon shark'],
    ['🦓', 'cebra zebra'],
    ['🦍', 'gorila'],
    ['🐘', 'elefante elephant'],
    ['🐫', 'camello camel'],
    ['🦒', 'jirafa giraffe'],
    ['🦔', 'erizo hedgehog'],
    ['🦩', 'flamenco flamingo'],
    ['🦜', 'loro parrot'],
    ['🦚', 'pavo real peacock'],
    ['🦢', 'cisne swan'],
    ['🍄', 'champinon mushroom seta'],
    ['🌵', 'cactus desierto'],
    ['🌴', 'palmera palm playa'],
    ['🌳', 'arbol tree'],
    ['🌲', 'pino conifer abeto'],
    ['🌱', 'planta semilla plant germinar'],
    ['🌿', 'hierba planta herb'],
    ['🍀', 'trebol clover suerte'],
    ['🎄', 'pino navidad christmas arbol'],
    ['🌻', 'girasol sunflower'],
    ['🌹', 'rosa rose flor regalo'],
    ['🌷', 'tulipan'],
    ['🌸', 'flor cerezo sakura cherry'],
    ['💐', 'ramo bouquet flores'],
    ['🌺', 'hibisco flor'],
    ['🌼', 'margarita daisy flor'],
    ['🌊', 'ola wave mar'],
    ['🌋', 'volcan volcano'],
    ['🏝️', 'isla island playa'],
    ['🏖️', 'playa beach tropical'],
    ['🌈', 'arco iris rainbow'],
    ['☀️', 'sol sun dia'],
    ['🌞', 'sol sonriente sun'],
    ['🌙', 'luna noche moon'],
    ['⭐', 'estrella star'],
    ['🌟', 'estrella brillante glowing'],
    ['✨', 'brillos sparkles destellos'],
    ['🌍', 'tierra globo mundo planet'],
    ['🪐', 'saturno planeta planet'],
  ]),
  C('Comida y bebida', [
    ['🍏', 'manzana verde apple'],
    ['🍎', 'manzana roja apple'],
    ['🍐', 'pera pear'],
    ['🍊', 'naranja orange'],
    ['🍋', 'limon'],
    ['🍌', 'platano banana'],
    ['🍉', 'sandia watermelon'],
    ['🍇', 'uvas grapes'],
    ['🍓', 'fresa strawberry'],
    ['🍒', 'cerezas cherries'],
    ['🍑', 'durazno melocoton peach'],
    ['🥭', 'mango'],
    ['🍍', 'pina pineapple'],
    ['🥥', 'coco coconut'],
    ['🥝', 'kiwi'],
    ['🍅', 'tomate jitomate'],
    ['🥑', 'aguacate avocado palta'],
    ['🥦', 'brocoli'],
    ['🥬', 'lechuga verdura verde'],
    ['🥒', 'pepino cucumber'],
    ['🌽', 'maiz'],
    ['🥕', 'zanahoria carrot'],
    ['🧄', 'ajo garlic'],
    ['🧅', 'cebolla onion'],
    ['🥔', 'papa patata potato'],
    ['🍠', 'camote batata sweet potato'],
    ['🥐', 'croissant pan'],
    ['🥖', 'baguette pan'],
    ['🍞', 'pan bread'],
    ['🥨', 'pretzel'],
    ['🧀', 'queso cheese'],
    ['🥚', 'huevo egg'],
    ['🍳', 'huevo frito sarten'],
    ['🧈', 'mantequilla butter'],
    ['🥓', 'tocino bacon panceta'],
    ['🥩', 'carne meat bistec'],
    ['🍗', 'muslo pollo drumstick'],
    ['🍖', 'pierna costilla carne'],
    ['🌭', 'perrito caliente hotdog'],
    ['🍔', 'hamburguesa burger'],
    ['🍟', 'papas fritas fries'],
    ['🍕', 'pizza'],
    ['🥪', 'sandwich bocadillo'],
    ['🌮', 'taco tortilla'],
    ['🌯', 'burrito wrap'],
    ['🥗', 'ensalada salad'],
    ['🍝', 'pasta espagueti spaghetti'],
    ['🍜', 'sopa ramen fideos'],
    ['🍣', 'sushi'],
    ['🍱', 'bento caja comida'],
    ['🍙', 'bolita arroz rice'],
    ['🍚', 'arroz rice'],
    ['🍛', 'curry'],
    ['🍲', 'guiso sopa stew estofado'],
    ['🥟', 'empanadilla dumpling gyoza'],
    ['🥡', 'comida para llevar takeout'],
    ['🍦', 'helado cone softice'],
    ['🍨', 'sunday copa helado'],
    ['🍩', 'dona donut rosquilla'],
    ['🍪', 'galleta cookie'],
    ['🎂', 'pastel tarta cumpleanos cake'],
    ['🍰', 'bizcocho tarta dulce cake'],
    ['🧁', 'cupcake magdalena'],
    ['🥧', 'pie tarta'],
    ['🍫', 'chocolate'],
    ['🍬', 'caramelo dulces candy'],
    ['🍭', 'piruleta lollipop chupetin'],
    ['🍯', 'miel honey'],
    ['🧃', 'jugo caja juice box'],
    ['🥤', 'refresco gaseosa soda milkshake'],
    ['🧋', 'te burbujas boba'],
    ['🍺', 'cerveza beer pinta'],
    ['🍻', 'brindis cheers cervezas'],
    ['🥂', 'champan copas brindis'],
    ['🍷', 'vino wine copa'],
    ['🥃', 'whisky copa coctel'],
    ['🍸', 'martini coctel cocktail'],
    ['🍹', 'tropical zumo coctel'],
    ['🥄', 'cuchara spoon'],
    ['🍴', 'tenedor cuchillo cubiertos'],
  ]),
  C('Actividad y deportes', [
    ['⚽', 'futbol soccer balon'],
    ['🏀', 'baloncesto basketball balon'],
    ['🏈', 'football americano'],
    ['⚾', 'beisbol baseball pelota'],
    ['🎾', 'tenis tennis raqueta'],
    ['🏐', 'voleibol volleyball'],
    ['🏉', 'rugby'],
    ['🎱', 'billar pool pelota'],
    ['🏓', 'ping pong tenis mesa'],
    ['🏸', 'badminton volante'],
    ['🥊', 'boxeo box guantes'],
    ['🥋', 'karate artes marciales judo'],
    ['⛳', 'golf'],
    ['⛸️', 'patinaje hielo skating'],
    ['🎿', 'esqui ski'],
    ['🏂', 'snowboard'],
    ['🏋️', 'pesas halterofilia gym'],
    ['🤸', 'gimnasia gimnasta'],
    ['🤺', 'esgrima fencing espada'],
    ['🏊', 'natacion nadar swim piscina'],
    ['🤽', 'waterpolo polo'],
    ['🚣', 'remo rowing bote'],
    ['🧗', 'escalada climbing montana'],
    ['🚴', 'ciclista bici bicicleta'],
    ['🏇', 'caballo carrera horse racing'],
    ['🏆', 'trofeo trophy premio campeon'],
    ['🥇', 'oro gold medalla primero'],
    ['🥈', 'plata silver medalla segundo'],
    ['🥉', 'bronce bronze medalla tercero'],
    ['🏅', 'medalla medal'],
    ['🎮', 'videojuegos gamepad consola'],
    ['🎲', 'dados dice azar suerte'],
    ['♟️', 'ajedrez chess'],
    ['🎯', 'diana target dardos objetivo'],
    ['🎳', 'bolos bowling'],
    ['🎤', 'microfono cantar karaoke'],
    ['🎧', 'auriculares audifonos musica'],
    ['🎼', 'partitura musica'],
    ['🎹', 'piano teclado musica'],
    ['🥁', 'tambor bateria drums'],
    ['🎷', 'saxofon'],
    ['🎺', 'trompeta trumpet'],
    ['🎸', 'guitarra guitar rock'],
    ['🎻', 'violin'],
    ['🎬', 'claqueta pelicula cine film'],
    ['🎨', 'pintura paleta artista art'],
    ['🎪', 'circo carpa'],
    ['🎟️', 'entradas boletos ticket'],
    ['🎭', 'teatro mascaras drama'],
    ['📷', 'camara foto fotografia camera'],
    ['🎥', 'camara video cine film'],
    ['🤿', 'buceo diving snorkel'],
  ]),
  C('Viajes', [
    ['🚗', 'coche auto car automovil'],
    ['🚕', 'taxi'],
    ['🚙', 'todoterreno suv'],
    ['🚌', 'autobus bus colectivo'],
    ['🚓', 'patrulla policia police'],
    ['🚑', 'ambulancia emergencia'],
    ['🚒', 'camion bomberos firetruck'],
    ['🚐', 'furgoneta van'],
    ['🚚', 'camion truck flete'],
    ['🚜', 'tractor granja'],
    ['🛴', 'patinete scooter'],
    ['🏍️', 'motocicleta moto'],
    ['🛵', 'motoneta vespa'],
    ['🚲', 'bicicleta bici bike'],
    ['✈️', 'avion plane viaje'],
    ['🛫', 'despegue takeoff'],
    ['🛬', 'aterrizaje landing'],
    ['🚁', 'helicoptero'],
    ['🚀', 'cohete rocket espacio'],
    ['🛸', 'ovni platillo ufo'],
    ['🚢', 'barco ship crucero'],
    ['⛵', 'velero sailboat vela'],
    ['🛶', 'piragua canoa kayak'],
    ['🚤', 'lancha speedboat'],
    ['🗺️', 'mapa mundo mapa'],
    ['🧭', 'brujula compas orientacion'],
    ['🏰', 'castillo castle'],
    ['🏛️', 'edificio columnas monumento'],
    ['🏗️', 'construccion obra grue'],
    ['🏖️', 'playa'],
    ['🏞️', 'parque natural paisaje'],
    ['🌇', 'atardecer ciudad dusk'],
    ['🌆', 'amanecer ciudad'], 
    ['🎠', 'carrusel tiovivo'],
    ['🎡', 'noria rueda feria'],
    ['🎢', 'montana rusa roller coaster'],
  ]),
  C('Objetos', [
    ['⌚', 'reloj watch pulsera'],
    ['📱', 'telefono celular movil smartphone'],
    ['💻', 'portatil laptop ordenador'],
    ['🖥️', 'monitor ordenador computadora'],
    ['🖨️', 'impresora printer'],
    ['⌨️', 'teclado keyboard'],
    ['🖱️', 'raton mouse pc'],
    ['💾', 'disquete disk floppy'],
    ['💿', 'cd disco'],
    ['📀', 'dvd'],
    ['📼', 'videocasete vhs video'],
    ['📸', 'camara flash foto'],
    ['📹', 'videocamara camcorder'],
    ['📺', 'television televisor tv'],
    ['📻', 'radio'],
    ['⏰', 'despertador reloj alarma'],
    ['⏱️', 'cronometro'],
    ['⏲️', 'temporizador timer'],
    ['🕰️', 'reloj pared'],
    ['📞', 'telefono fijo phone'],
    ['📠', 'fax'],
    ['🔋', 'bateria pilas carga'],
    ['🔌', 'enchufe plug corriente'],
    ['💡', 'bombilla luz idea lightbulb'],
    ['🔦', 'linterna flashlight'],
    ['🕯️', 'vela candela'],
    ['🪫', 'bateria baja carga'],
    ['🧯', 'extintor fuego'],
    ['🪜', 'escalera ladder'],
    ['🧰', 'caja herramientas tool box'],
    ['🧲', 'iman magneto'],
    ['🪓', 'hacha axe'],
    ['🔪', 'cuchillo knife'],
    ['🏹', 'arco flecha organizacion'],
    ['🛡️', 'escudo shield defensa'],
    ['🔧', 'llave inglesa herramienta wrench'],
    ['🔨', 'martillo hammer'],
    ['🛠️', 'herramientas tools'],
    ['⚙️', 'engranaje gear configuracion ajustes'],
    ['🔒', 'candado cerrado seguro lock'],
    ['🔓', 'candado abierto unlocked'],
    ['🔑', 'llave key secreto'],
    ['🗝️', 'llave antigua'],
    ['🔫', 'pistola agua'],
    ['💣', 'bomba explosivo'],
    ['🗑️', 'papelera basura borrar trash'],
    ['📥', 'bandeja entrada inbox'],
    ['📤', 'bandeja salida outbox'],
    ['📚', 'libros stack'],
    ['📖', 'libro abierto lectura read'],
    ['📘', 'libro azul'],
    ['📗', 'libro verde'],
    ['📙', 'libro naranja'],
    ['📄', 'documento hoja papel page'],
    ['📜', 'pergamino scroll'],
    ['📊', 'grafica bar chart estadisticas'],
    ['📈', 'grafica subida chart crecimiento'],
    ['📉', 'grafica bajada chart decremento'],
    ['📰', 'periodico noticias news'],
    ['📓', 'cuaderno notebook'],
    ['📝', 'nota lapiz papel memo'],
    ['✏️', 'lapiz pencil'],
    ['🖊️', 'boligrafo pen'],
    ['🖌️', 'brocha pincel'],
    ['🖍️', 'crayon cerita'],
    ['📏', 'regla ruler medida'],
    ['📐', 'escuadra regla'],
    ['✂️', 'tijeras scissors cortar'],
    ['🔗', 'enlace eslabon link'],
    ['📎', 'clip sujetapapeles'],
    ['📌', 'chincheta pin ubicacion'],
    ['📍', 'pin ubicacion lugar marcador'],
    ['🏷️', 'etiqueta tag precio'],
    ['🎈', 'globo balloon fiesta'],
    ['🎉', 'confeti fiesta celebrate'],
    ['🎊', 'bola confeti'],
    ['🎁', 'regalo presente caja'],
    ['📅', 'calendario fecha agenda'],
    ['📆', 'calendario deslizable'],
    ['🗂️', 'organizador fichas'],
    ['📁', 'carpeta folder archivo'],
    ['📂', 'carpeta abierta'],
    ['🖼️', 'cuadro imagen foto marco'],
    ['🎞️', 'carrete pelicula'],
    ['💾', 'disco'],
    ['🗄️', 'archivador'],
    ['🗳️', 'urna votacion'],
  ]),
  C('Símbolos', [
    ['✔️', 'marca check verificar correcto listo'],
    ['❌', 'cruz error incorrecto no'],
    ['➕', 'mas suma'],
    ['➖', 'menos resta'],
    ['❓', 'interrogacion pregunta question dudas'],
    ['❗', 'exclamacion admiracion'],
    ['💲', 'dolar dinero signo'],
    ['🆕', 'nuevo new'],
    ['🆒', 'guay cool nuevo'],
    ['🔤', 'abecedario abc letras'],
    ['🔢', 'numeros 123'],
    ['🔡', 'letras minusculas'],
    ['🔠', 'letras mayusculas'],
    ['🔥', 'fuego fire calor'],
    ['⚡', 'rayo electricidad energia'],
    ['💧', 'gota agua'],
    ['💦', 'gotas sudor agua'],
    ['💨', 'viento humo'],
    ['🫧', 'burbujas jabon bubbles'],
    ['💥', 'explosion boom impacto'],
    ['🚀', 'cohete rapido'],
    ['💤', 'zzz dormir sueno'],
    ['💫', 'estrella fugaz girando'],
    ['⏳', 'reloj arena tiempo'],
    ['⌛', 'reloj arena terminando'],
    ['🪪', 'tarjeta identificacion id'],
    ['🧮', 'abaco calculo'],
    ['🗿', 'moai estatua'],
    ['🏳️', 'bandera blanca'],
    ['🚩', 'bandera meta objetivo'],
    ['🏴', 'bandera negra'],
    ['🏴‍☠️', 'bandera pirata'],
    ['🇪🇸', 'bandera espana'],
    ['🇦🇷', 'bandera argentina'],
    ['🇲🇽', 'bandera mexico'],
    ['🇬🇧', 'bandera inglaterra reino unido'],
    ['🇺🇸', 'bandera estados unidos'],
  ]),
];